#!/usr/bin/perl
##
##                  $Id: assemble 14646 2011-01-17 16:52:34Z neil.middleton $
##     $LastChangedDate: 2011-01-17 16:52:34 +0000 (Mon, 17 Jan 2011) $
## $LastChangedRevision: 14646 $
##       $LastChangedBy: neil.middleton $
##             $HeadURL: https://sami.cdt.int.thomsonreuters.com/svn/gms_gmi/trunk/infrastructure/tools/webfrontend/assemble $
##

#
# Assembly script 
#
# Run this from the directory containing the component you want to
# assemble. Supply the directory holding the release lib you are
# assembling to as an option.
#

use strict;
use Assembly;
use File::Copy;

startAssemble();
sendToDirectory();

#Process the directory tree
sendToDirectory(
  -requiredEnvValue => 'gmidbserver.GUI2DBuser'
);

